production:

development:
  adapter: postgresql
  database: new_sanctuary_asylum_development
  host: localhost
  pool: 30

test: &test
  adapter: postgresql
  database: new_sanctuary_asylum_test
  host: localhost